### ISSUE TITLE
I2C write buffer bug

### ISSUE THREAD

**Issue by mklomp** [MrYsLab/telemetrix#2]
When testing the IC@ functionality with my SDD1306 OLED I ran into some weird behaviour. Thanks to the new debug info I was able to fix it. The first address in https://github.com/MrYsLab/telemetrix/blob/6bbcdacaba76533b10570cf8b5c030948cbc0dae/phase3/telemetrix/telemetrix.py#L504 should be len(args).

**Comment by MrYsLab** [comment]
Fixed with release 0.1.4.

Great catch. Thanks.
