### ISSUE TITLE
Small typos in the documentation for Telemetrix4Arduino

### ISSUE THREAD

**Issue by MegaMosquito** [MrYsLab/telemetrix#46]
On this documentation page:

- [https://mryslab.github.io/telemetrix/telemetrix4arduino](https://mryslab.github.io/telemetrix/telemetrix4arduino/)

In 4 places it says "Telemtrix4Arduino" instead of "Telemetrix4Arduino".

These are the places:

1. Page title: "Telemetrix and **Telemtrix**-AIO User's Guide" (typo on second one)
2. Left pane title: "Telemetrix and **Telemtrix**-AIO User's Guide" (typo on second one)
3. Right pane title: "**Telemtrix**4Arduino"
4. Right pane item: "2. Enter "**Telemtrix**4Arduino in the search box." (this line is also missing the **closing "**)

**Comment by MrYsLab** [comment]
Thanks for letting me know. I have corrected the document, and it is available online now.
Thanks again.
