### ISSUE TITLE
i2c_write to MCP4725

### ISSUE THREAD

**Issue by phthalimid** [MrYsLab/telemetrix#53]
Hi Alan,

I really love Telemetrix. Great work! However, I've got one major issue: I didn't manage to write to a DAC chip (MCP4725) via i2c_write(). Whatever args I give, I get always the same error message:

"TypeError: 'bytes' object cannot be interpreted as an integer"

Here is my code fragment:

mcp4725 = b'\x60'
buffer = [0, 0]
board.i2c_write(mcp4725, buffer)

As 'buffer', I tried pretty much everything that came to my mind. Some examples:

buffer = [0]
buffer = [b'\x00', b'\x00']
buffer = bytearray(b'\x00\x00')
... and many others. They all resulted in the same error message.

I hope you can help.

**Comment by MrYsLab** [comment]
I am closing this issue and have opened a new issue to clarify the comments for i2c read and write. See issue #54.

You may still add a comment to this issue even though it is closed, and I will see it.
