### ISSUE TITLE
28BYJ-48 Stepper motor with ULN2003 not working properly

### ISSUE THREAD

**Issue by MrYsLab** [MrYsLab/telemetrix#61]
The motor vibrates but does not turn using this motor/controller combination. Using a NEMA 17 12-volt motor with a TB6600 controller works correctly.

I tried using an external high-current supply for the ULN2003, which did not solve the problem. 

This will take further investigation to determine the cause.

**Comment by MrYsLab** [comment]
[@diegormsouza](https://github.com/diegormsouza)
I have figured out what is going on, but unfortunately, the 28BYJ-48 can't be supported by telemetrix.

The reason is that there is a timing issue. When one runs an AccelStepper sketch (non-telemetrix) and an AccelStepper method such as the distanceToGo method is called, the value is available very quickly.

When using telemetrix, however, there is a delay when sending the command to the Arduino and another delay in the returning reply. The run method, therefore, is not being called quickly enough.

When using a controller such as the TB6600, this disparity in timing is internally masked, and things magically work.

I will remove the reference to the 28BYJ-48 in the stepper examples and add a note that the 28BYJ-48 is not supported.

I am closing this issue, but please feel free to leave any further comments here.

**Comment by diegormsouza** [comment]
Thanks for verifying that @MrYsLab !

I understand. I'll test a TB6600 controller when I have the opportunity.

**Comment by stellaurum** [comment]
@MrYsLab Wanted to check to confirm whether the 28BYJ-48 is supported or not? This comment chain seems to imply not, however the references are still in place within the examples.

**Comment by MrYsLab** [comment]
@stellaurum I understand why you are confused.  Based on the testing with the 28BYJ-48 and ULN2003 Driver I probably should have removed the comments. That being said, I found [this code ](https://github.com/BretStateham/28BYJ-48/blob/master/Arduino/Code/S07_AccelStepperDemo/S07_AccelStepperDemo.ino)that supposedly works as an Arduino sketch with Accelstepper. I will test the sketch, and if it works, I will port it to a Telemetrix client and let you know if I am successful or not.
If I am unable to get it working, I will remove the comments.

**Comment by stellaurum** [comment]
@MrYsLab I was actually able to get it working most shortly after leaving that comment. As far as I can tell, the Telemetrix examples do, in fact, work mostly as is, the issues I was experiencing that led to me finding this issue chain were a result of typos on my end. That being said, the examples should probably be updated to the following: `set_pin_mode_stepper(interface=4, pin1=8, pin2=9, pin3=10,
    # pin4=11)`. Anyone using the 28BYJ-48 will likely be using the following layout as it is included with purchases of it:

![Image](https://github.com/user-attachments/assets/70540f13-56cd-4ac7-9a39-cb1d99c3e5f8)

**Comment by MrYsLab** [comment]
Thanks for letting me know. Since it is working for you, I will not be testing it.
