### ISSUE TITLE
run stepper motor at constant speed and reverse direction

### ISSUE THREAD

**Issue by mkodanda** [MrYsLab/telemetrix#62]
Dear Mr Yorinks,

I stumbled on this nice piece of software, found it very nice, thanks for creating!

I would like to run a stepper motor with TB6600 driver at different constant speeds. I need to reverse the direction of rotation, now and then. The example "stepper_continuous.py" appears to demonstrate just the kind of thing I needed. However, I am unable to reverse the direction using sequential calls of the methods stepper_set_max_speed(), stepper_set_speed(),  and stepper_run_speed().

The stepper_run_speed() cannot take a negative number.

I have gone through the other methods, but couldn't find a solution. Please point me in the right direction.

Thanks and regards,
Kodanda

**Comment by MrYsLab** [comment]
@mkodanda Thanks for the question. The direction is set in the [stepper_set_speed method.](https://htmlpreview.github.io/?https://github.com/MrYsLab/telemetrix/blob/master/html/telemetrix/index.html#telemetrix.telemetrix.Telemetrix.stepper_set_speed). 

Please try changing the speed from positive to negative, and let me know if that solves your issue.

**Comment by MrYsLab** [comment]
@mkodanda Thanks for the question. The stepper_set_speed method should allow you to set a negative value, but it doesn't. I will fix this and let you know when it is available.

**Comment by MrYsLab** [comment]
I will need a few days to update both telemetrix and Telemetrix4Arduino and test it.
I will let you know when it is ready as soon as possible.
Thanks.

**Comment by mkodanda** [comment]
Thank you Mr. Yorinks for your quick response! I shall wait for the fix.
Thanks
Kodanda

**Comment by MrYsLab** [comment]
I have implemented the fixes. However, I am not able to upload to pypi. PyPI has updated to a 2-level authentication scheme, causing problems with Github. GitHub has also made changes, so it will probably take me a while to figure it out. What used to be simple is now unbelievably complicated.

You can still install the changes manually. If you go to [this page](https://github.com/MrYsLab/telemetrix) and click the green code button, you will download a .zip file.
![Screenshot from 2023-09-24 11-43-22](https://github.com/MrYsLab/telemetrix/assets/5189838/702a433a-7cba-4c78-87f0-0b2011df9399)

Unzip the file and find the setup.py file. You can install the library by typing python setup.py.

You may need to use python3 setup.py.

Next, you must install the latest version of Telemetrix4Arduino (5.3.1) on your Arduino board. It may take Arduino a day or so to make it available in Arduino IDE. You may also do a manual install by getting the code from [here.](https://github.com/MrYsLab/Telemetrix4Arduino)

I will leave this issue open until I can figure out how to upload to PyPI.

**Comment by MrYsLab** [comment]
@MrYsLab The Python code is now available on PyPI. The release is 1.31.
The Telemetrix4Arduino library is not yet available through the Arduino IDE. I will monitor it and let you know when it becomes available.

**Comment by MrYsLab** [comment]
@mkodanda Telemetrix4Arduino is now available on the Arduino IDE.

**Comment by MrYsLab** [comment]
@mkodanda Please install Telemetrix4Arduino version 5.3.3 using the Arduino IDE. The previous version did not fix the issue. I apologize for the mixup.
